import { requireAdmin } from "@/lib/admin/auth";
import { getAdminTrip } from "@/lib/admin/data";
import { createDay, deleteDay, moveDay, saveDay } from "@/lib/admin/actions";
import { ConfirmSubmit } from "@/components/admin/ConfirmSubmit";

export default async function AdminDaysPage({ params }: { params: Promise<{ tripId: string }> }) {
  const { client } = await requireAdmin(); const { tripId } = await params; const trip = await getAdminTrip(client, tripId); if (!trip) return null;
  return <section className="admin-section"><div className="admin-page-heading"><div><span className="section-label">{trip.title}</span><h1>Jornadas</h1><p>{trip.days.length} jornadas ordenadas para el relato.</p></div></div><form action={createDay} className="admin-editor-card admin-create-card"><input type="hidden" name="tripSlug" value={trip.slug} /><div className="editor-card-heading"><strong>Nueva jornada</strong></div><div className="admin-form-grid"><label>Fecha<input type="date" name="date" required /></label><label>Titulo<input name="title" required /></label><label>Ciudad o trayecto<input name="location" /></label><label>Fase<input name="phase" /></label><label className="field-wide">Resumen<textarea name="summary" rows={2} /></label></div><button className="admin-primary-link" type="submit">Crear jornada</button></form><div className="admin-editor-stack">{trip.days.map((day, index) => <article className="admin-editor-card" key={day.id}><div className="editor-card-heading"><span className="day-number">Dia {day.dayNumber}</span><strong>{day.date}</strong><div className="admin-card-actions"><form action={moveDay}><input type="hidden" name="tripSlug" value={trip.slug} /><input type="hidden" name="dayId" value={day.id} /><input type="hidden" name="direction" value="up" /><button type="submit" disabled={index === 0}>Subir</button></form><form action={moveDay}><input type="hidden" name="tripSlug" value={trip.slug} /><input type="hidden" name="dayId" value={day.id} /><input type="hidden" name="direction" value="down" /><button type="submit" disabled={index === trip.days.length - 1}>Bajar</button></form></div></div><form action={saveDay}><input type="hidden" name="tripSlug" value={trip.slug} /><input type="hidden" name="dayId" value={day.id} /><div className="admin-form-grid"><label>Numero<input type="number" min="0" name="dayNumber" defaultValue={day.dayNumber} required /></label><label>Fecha<input type="date" name="date" defaultValue={day.date} required /></label><label>Titulo<input name="title" defaultValue={day.title} required /></label><label>Ciudad o trayecto<input name="location" defaultValue={day.location} required /></label><label>Fase<input name="phase" defaultValue={day.phase} /></label><label className="field-wide">Resumen<textarea name="summary" defaultValue={day.summary} rows={3} /></label></div><button type="submit" className="admin-primary-link">Guardar jornada</button></form><form action={deleteDay}><input type="hidden" name="tripSlug" value={trip.slug} /><input type="hidden" name="dayId" value={day.id} /><ConfirmSubmit className="admin-danger-link" message="Eliminar esta jornada y sus asignaciones?">Eliminar jornada</ConfirmSubmit></form></article>)}</div></section>;
}
