import { requireAdmin } from "@/lib/admin/auth";
import { getAdminTrip } from "@/lib/admin/data";
import { activateHeroSet, createHeroSet, saveHeroSet } from "@/lib/admin/actions";
import { ConfirmSubmit } from "@/components/admin/ConfirmSubmit";

export default async function AdminCoversPage({ params }: { params: Promise<{ tripId: string }> }) {
  const { client } = await requireAdmin(); const { tripId } = await params; const trip = await getAdminTrip(client, tripId); if (!trip) return null;
  const media = trip.media.filter((item) => item.reviewStatus !== "rejected");
  return <section className="admin-section"><div className="admin-page-heading"><div><span className="section-label">{trip.title}</span><h1>Portadas</h1><p>Crea variantes, asigna slots y conserva la seleccion aleatoria si se desea.</p></div></div><form action={createHeroSet} className="admin-editor-card admin-create-card"><input type="hidden" name="tripSlug" value={trip.slug} /><div className="admin-form-grid"><label>Nombre de variante<input name="name" placeholder="e" required /></label><label>Layout<select name="layout" defaultValue="collage"><option value="collage">Collage</option><option value="slideshow">Slideshow</option><option value="video">Video</option></select></label></div><button className="admin-primary-link" type="submit">Crear portada</button></form><div className="admin-cover-grid">{trip.heroSets.map((heroSet) => <article className={`admin-cover-card${heroSet.isActive ? " is-active" : ""}`} key={heroSet.id}><div className="admin-cover-preview"><span>Portada {heroSet.name.toUpperCase()}</span><small>{heroSet.layout}</small></div><form action={saveHeroSet} className="admin-cover-editor"><input type="hidden" name="tripSlug" value={trip.slug} /><input type="hidden" name="heroSetId" value={heroSet.id} /><label>Nombre<input name="name" defaultValue={heroSet.name} required /></label><label>Layout<select name="layout" defaultValue={heroSet.layout}><option value="collage">Collage</option><option value="slideshow">Slideshow</option><option value="video">Video</option></select></label><fieldset><legend>Medios y foco por slot</legend><div className="admin-check-grid">{media.map((item) => <label key={item.id}><span><input type="checkbox" name="mediaId" value={item.id} defaultChecked={heroSet.mediaIds.includes(item.id)} /> {item.originalFileName}</span><span><input type="number" name={`focusX_${item.id}`} min="0" max="100" defaultValue="50" aria-label={`Foco horizontal ${item.originalFileName}`} /> x <input type="number" name={`focusY_${item.id}`} min="0" max="100" defaultValue="50" aria-label={`Foco vertical ${item.originalFileName}`} /></span></label>)}</div></fieldset><button type="submit" className="admin-primary-link">Guardar portada</button></form><div className="admin-cover-status"><strong>{heroSet.isActive ? "Activa" : "Disponible"}</strong><span>{heroSet.mediaIds.length} medios asignados</span>{!heroSet.isActive && <form action={activateHeroSet}><input type="hidden" name="tripSlug" value={trip.slug} /><input type="hidden" name="heroSetId" value={heroSet.id} /><ConfirmSubmit message="Cambiar la portada activa? El cambio se refleja en la web publica." className="admin-secondary-link">Activar portada</ConfirmSubmit></form>}</div></article>)}</div></section>;
}
