import { requireAdmin } from "@/lib/admin/auth";
import { getAdminTrip } from "@/lib/admin/data";
import { createSection, deleteSection, saveSection } from "@/lib/admin/actions";
import { ConfirmSubmit } from "@/components/admin/ConfirmSubmit";

export default async function AdminSectionsPage({ params }: { params: Promise<{ tripId: string }> }) {
  const { client } = await requireAdmin();
  const { tripId } = await params;
  const trip = await getAdminTrip(client, tripId);
  if (!trip) return null;
  const selectedMedia = trip.media.filter((media) => media.reviewStatus === "selected");
  return <section className="admin-section"><div className="admin-page-heading"><div><span className="section-label">{trip.title}</span><h1>Secciones</h1><p>Contenido sin fecha exacta, ordenado como galería y cerrado inicialmente.</p></div></div>
    <form action={createSection} className="admin-editor-card admin-create-card"><input type="hidden" name="tripSlug" value={trip.slug} /><div className="editor-card-heading"><strong>Nueva sección adicional</strong></div><div className="admin-form-grid"><label>Título<input name="title" required /></label><label>Después de la jornada<select name="afterDayNumber" defaultValue=""><option value="">Al final del viaje</option>{trip.days.map((day) => <option value={day.dayNumber} key={day.id}>Día {day.dayNumber} · {day.title}</option>)}</select></label><label className="field-wide">Descripción<textarea name="description" rows={3} /></label><label className="field-wide">Medios seleccionados<select name="mediaId" multiple size={Math.min(8, Math.max(4, selectedMedia.length))}>{selectedMedia.map((media) => <option key={media.id} value={media.id}>{media.originalFileName}</option>)}</select></label></div><button className="admin-primary-link" type="submit">Crear sección</button></form>
    <div className="admin-editor-stack">{trip.sections.map((section) => <article className="admin-editor-card" key={section.id}><div className="editor-card-heading"><strong>Sección {section.displayOrder + 1}</strong><span>Galería cerrada inicialmente</span></div><form action={saveSection}><input type="hidden" name="tripSlug" value={trip.slug} /><input type="hidden" name="sectionId" value={section.id} /><div className="admin-form-grid"><label>Título<input name="title" defaultValue={section.title} required /></label><label>Orden<input type="number" min="0" name="displayOrder" defaultValue={section.displayOrder} required /></label><label>Después de la jornada<select name="afterDayNumber" defaultValue={section.afterDayNumber === null ? "" : String(section.afterDayNumber)}><option value="">Al final del viaje</option>{trip.days.map((day) => <option value={day.dayNumber} key={day.id}>Día {day.dayNumber} · {day.title}</option>)}</select></label><label className="field-wide">Descripción<textarea name="description" defaultValue={section.description} rows={3} /></label><label className="field-wide">Medios seleccionados<select name="mediaId" multiple size={Math.min(8, Math.max(4, selectedMedia.length))} defaultValue={section.mediaIds}>{selectedMedia.map((media) => <option key={media.id} value={media.id}>{media.originalFileName}</option>)}</select></label></div><button className="admin-primary-link" type="submit">Guardar sección</button></form><form action={deleteSection}><input type="hidden" name="tripSlug" value={trip.slug} /><input type="hidden" name="sectionId" value={section.id} /><ConfirmSubmit className="admin-danger-link" message="¿Eliminar esta sección y sus asignaciones?">Eliminar sección</ConfirmSubmit></form></article>)}</div>
  </section>;
}
