import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { loadEnvConfig } from "@next/env";
import sharp from "sharp";
import { HeadObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { createSupabaseAdminClient } from "../lib/supabase/client";

type Mode = "dry-run" | "import" | "verify";
type MediaKind = "image" | "video";
type PlaceConfig = { key: string; name: string; city: string; zone: string; category: string; wikipediaUrl: string | null; latitude?: number; longitude?: number };
type DayConfig = { number: number; date: string; title: string; location: string; phase: string; summary: string };
type SectionConfig = { key: string; title: string; description: string };
type TripConfig = { slug: string; title: string; folder: string; startDate: string; endDate: string; country: string; intro: string; route: Array<{ name: string; region: string }>; days: DayConfig[]; places: PlaceConfig[]; sections: SectionConfig[] };
type SourceRecord = { absolutePath: string; relativePath: string; sourceFolder: string; originalFileName: string; extension: string; sourcePathHash: string; sourceBytes: number; kind: MediaKind; date: string | null; day: DayConfig | null; place: PlaceConfig | null; section: SectionConfig | null; mediaId: string; order: number };
type Prepared = { objects: PreparedObject[]; mediaType: MediaKind; width: number; height: number; duration?: number };
type PreparedObject = { key: string; body: Buffer; contentType: string; sha256: string };

const projectRoot = process.env.TRAVEL_PROJECT_ROOT?.trim() || process.cwd();
loadEnvConfig(projectRoot);
const mode = (process.argv[2] || "dry-run") as Mode;
if (!(["dry-run", "import", "verify"] as Mode[]).includes(mode)) throw new Error("Modo invalido. Usa dry-run, import o verify.");
const baseSourceRoot = process.env.TRAVEL_CITY_SOURCE_ROOT?.trim() || path.join(process.env.USERPROFILE || os.homedir(), "Downloads", "fotos para imanes");
const derivativeRoot = path.join(os.tmpdir(), "travel-magnets-city-derived");
const cacheControl = "public,max-age=31536000,immutable";

const configs: TripConfig[] = [
  {
    slug: "liverpool", title: "Liverpool", folder: "Liverpool", startDate: "2019-04-18", endDate: "2019-04-20", country: "Reino Unido",
    intro: "Un recorrido personal por Liverpool, su patrimonio musical, sus edificios y una excursion a Chester.",
    route: [{ name: "Liverpool", region: "Reino Unido" }, { name: "Chester", region: "Reino Unido" }],
    days: [
      { number: 0, date: "2019-04-18", title: "Liverpool y The Cavern Club", location: "Liverpool", phase: "Destino", summary: "Primeras imagenes fechadas del recorrido por Liverpool y The Cavern Club." },
      { number: 1, date: "2019-04-19", title: "Liverpool", location: "Liverpool", phase: "Destino", summary: "Arquitectura, Chinatown y Royal Albert Dock durante la jornada en Liverpool." },
      { number: 2, date: "2019-04-20", title: "Excursion a Chester", location: "Chester", phase: "Excursion", summary: "Jornada fechada en Chester." },
    ],
    places: [
      { key: "liverpool", name: "Liverpool", city: "Liverpool", zone: "Ciudad", category: "activity", wikipediaUrl: "https://es.wikipedia.org/wiki/Liverpool" },
      { key: "cavern-club", name: "The Cavern Club", city: "Liverpool", zone: "Mathew Street", category: "activity", wikipediaUrl: "https://es.wikipedia.org/wiki/Cavern_Club" },
      { key: "catedral-liverpool", name: "Catedral de Liverpool", city: "Liverpool", zone: "Centro", category: "religious", wikipediaUrl: "https://es.wikipedia.org/wiki/Catedral_de_Liverpool" },
      { key: "chinatown", name: "Chinatown", city: "Liverpool", zone: "Centro", category: "activity", wikipediaUrl: null },
      { key: "royal-albert-dock", name: "Royal Albert Dock", city: "Liverpool", zone: "Waterfront", category: "monument", wikipediaUrl: "https://es.wikipedia.org/wiki/Royal_Albert_Dock" },
      { key: "chester", name: "Chester", city: "Chester", zone: "Centro historico", category: "activity", wikipediaUrl: "https://es.wikipedia.org/wiki/Chester" },
    ],
    sections: [
      { key: "streets", title: "Calles de Liverpool", description: "Fotografias generales de las calles de Liverpool, conservadas sin asignar una fecha de jornada." },
      { key: "album", title: "Recuerdos del album", description: "Fotografias recuperadas de un album fisico. Se conservan como una seccion independiente y cerrada para revisarlas o sustituirlas desde el panel." },
    ],
  },
  {
    slug: "londres-2025", title: "Londres 2025", folder: "Londres", startDate: "2025-04-26", endDate: "2025-04-27", country: "Reino Unido",
    intro: "Un recorrido urbano por Londres en 2025, entre monumentos reconocibles, mercados y calles de la ciudad.",
    route: [{ name: "Londres", region: "Reino Unido" }, { name: "Big Ben", region: "Westminster" }, { name: "Tower Bridge", region: "Tower Hamlets" }, { name: "Camden Market", region: "Camden" }],
    days: [
      { number: 0, date: "2025-04-26", title: "Big Ben y Tower Bridge", location: "Londres", phase: "Destino", summary: "Jornada fechada en las carpetas de Big Ben y Tower Bridge." },
      { number: 1, date: "2025-04-27", title: "Camden Market", location: "Londres", phase: "Destino", summary: "Jornada fechada en Camden Market." },
    ],
    places: [
      { key: "londres", name: "Londres", city: "Londres", zone: "Ciudad", category: "activity", wikipediaUrl: "https://es.wikipedia.org/wiki/Londres" },
      { key: "big-ben", name: "Big Ben", city: "Londres", zone: "Westminster", category: "monument", wikipediaUrl: "https://es.wikipedia.org/wiki/Big_Ben" },
      { key: "tower-bridge", name: "Tower Bridge", city: "Londres", zone: "Tower Hamlets", category: "monument", wikipediaUrl: "https://es.wikipedia.org/wiki/Puente_de_la_Torre" },
      { key: "camden-market", name: "Camden Market", city: "Londres", zone: "Camden", category: "activity", wikipediaUrl: "https://es.wikipedia.org/wiki/Camden_Market" },
    ],
    sections: [{ key: "streets", title: "Calles de Londres", description: "Fotografias generales de Londres conservadas como contenido no fechado porque la carpeta no fija una jornada concreta." }],
  },
  {
    slug: "frankfurt", title: "Frankfurt", folder: "Frankfurt", startDate: "2022-06-09", endDate: "2022-06-12", country: "Alemania",
    intro: "Un recorrido por Colonia, Coblenza, Frankfurt y el Niederwalddenkmal durante cuatro jornadas de junio de 2022.",
    route: [{ name: "Colonia", region: "Alemania" }, { name: "Coblenza", region: "Alemania" }, { name: "Frankfurt", region: "Alemania" }, { name: "Niederwalddenkmal", region: "Rudesheim am Rhein" }],
    days: [
      { number: 0, date: "2022-06-09", title: "Colonia", location: "Colonia", phase: "Destino", summary: "Jornada fechada en Colonia." },
      { number: 1, date: "2022-06-10", title: "Coblenza", location: "Coblenza", phase: "Destino", summary: "Jornada fechada en Coblenza y el entorno del Rin." },
      { number: 2, date: "2022-06-11", title: "Frankfurt", location: "Frankfurt", phase: "Destino", summary: "Jornada fechada en Frankfurt." },
      { number: 3, date: "2022-06-12", title: "Niederwalddenkmal", location: "Rudesheim am Rhein", phase: "Excursion", summary: "Jornada fechada en Niederwalddenkmal y su entorno." },
    ],
    places: [
      { key: "colonia", name: "Colonia", city: "Colonia", zone: "Ciudad", category: "activity", wikipediaUrl: "https://es.wikipedia.org/wiki/Colonia_%28Alemania%29" },
      { key: "coblenza", name: "Coblenza", city: "Coblenza", zone: "Ciudad", category: "activity", wikipediaUrl: "https://es.wikipedia.org/wiki/Coblenza" },
      { key: "frankfurt", name: "Frankfurt", city: "Frankfurt", zone: "Ciudad", category: "activity", wikipediaUrl: "https://es.wikipedia.org/wiki/Fr%C3%A1ncfort_del_Meno" },
      { key: "niederwalddenkmal", name: "Niederwalddenkmal", city: "Rudesheim am Rhein", zone: "Niederwald", category: "monument", wikipediaUrl: null },
    ],
    sections: [],
  },
];

function required(name: string) { const value = process.env[name]?.trim(); if (!value || /[\s"']/.test(value)) throw new Error("Falta o no es valida la variable " + name + "."); return value; }
function stableUuid(value: string) { const bytes = createHash("sha1").update("travel-magnets:" + value).digest("hex").slice(0, 32).split(""); bytes[12] = "5"; bytes[16] = (parseInt(bytes[16], 16) & 3 | 8).toString(16); return bytes.slice(0, 8).join("") + "-" + bytes.slice(8, 12).join("") + "-" + bytes.slice(12, 16).join("") + "-" + bytes.slice(16, 20).join("") + "-" + bytes.slice(20).join(""); }
function sha256(value: Buffer | string) { return createHash("sha256").update(value).digest("hex"); }
function plain(value: string) { return value.normalize("NFKD").replace(/[\u0300-\u036f]/g, ""); }
function dateFromFolder(folder: string) { const match = folder.match(/(\d{2})(?:-|)(\d{2})(?:-|)(\d{2})$/); if (!match) return null; const [day, month, year] = match.slice(1); return `20${year}-${month}-${day}`; }
function hasExtension(file: string) { return /\.(jpe?g|png|webp|mp4|mov|avi)$/i.test(file); }
function sourceConfig(folder: string, relativePath: string, configsForFolder: TripConfig) {
  const top = plain(relativePath.split("/")[0]).toLowerCase();
  const place = configsForFolder.places.find((candidate) => {
    if (configsForFolder.slug === "liverpool") return (top.includes("cavern") && candidate.key === "cavern-club") || (top.includes("catedral") && candidate.key === "catedral-liverpool") || (top.includes("chinatown") && candidate.key === "chinatown") || (top.includes("royal albert") && candidate.key === "royal-albert-dock") || (top.includes("chester") && candidate.key === "chester") || (top.includes("calles") && candidate.key === "liverpool");
    if (configsForFolder.slug === "londres-2025") return (top.includes("big ben") && candidate.key === "big-ben") || (top.includes("tower bridge") && candidate.key === "tower-bridge") || (top.includes("candem") && candidate.key === "camden-market") || (top.includes("calles") && candidate.key === "londres");
    return (top.includes("colonia") && candidate.key === "colonia") || (top.includes("coblenza") && candidate.key === "coblenza") || (top.includes("frankfurt") && candidate.key === "frankfurt") || (top.includes("niederwald") && candidate.key === "niederwalddenkmal");
  }) ?? null;
  const section = configsForFolder.sections.find((candidate) => (configsForFolder.slug === "liverpool" && ((top.includes("calles") && candidate.key === "streets") || (top.includes("recopilacion") && candidate.key === "album"))) || (configsForFolder.slug === "londres-2025" && top.includes("calles") && candidate.key === "streets")) ?? null;
  const date = dateFromFolder(relativePath.split("/")[0]);
  const day = date ? configsForFolder.days.find((candidate) => candidate.date === date) ?? null : null;
  return { place, section, date: section ? null : date, day: section ? null : day };
}

async function walk(directory: string): Promise<string[]> { const entries = await fs.readdir(directory, { withFileTypes: true }); const files: string[] = []; for (const entry of entries) { const absolute = path.join(directory, entry.name); if (entry.isDirectory()) files.push(...await walk(absolute)); else if (hasExtension(entry.name)) files.push(absolute); } return files; }
async function scan(config: TripConfig) {
  const sourceRoot = path.join(baseSourceRoot, config.folder);
  const files = await walk(sourceRoot);
  const groups = new Map<string, string[]>();
  const all: SourceRecord[] = [];
  let sourceBytes = 0;
  for (const [order, absolutePath] of files.sort().entries()) {
    const relativePath = path.relative(sourceRoot, absolutePath).replaceAll("\\", "/");
    const bytes = await fs.readFile(absolutePath);
    const stat = await fs.stat(absolutePath);
    const digest = sha256(bytes);
    sourceBytes += stat.size;
    groups.set(digest, [...(groups.get(digest) ?? []), relativePath]);
    const mapped = sourceConfig(relativePath, relativePath, config);
    const extension = path.extname(relativePath).toLowerCase();
    all.push({ absolutePath, relativePath, sourceFolder: path.dirname(relativePath).replaceAll("\\", "/"), originalFileName: path.basename(relativePath), extension, sourcePathHash: digest, sourceBytes: stat.size, kind: extension === ".mp4" || extension === ".mov" || extension === ".avi" ? "video" : "image", date: mapped.date, day: mapped.day, place: mapped.place, section: mapped.section, mediaId: stableUuid(`media:${config.slug}:${relativePath}`), order });
  }
  const duplicates = [...groups.values()].filter((group) => group.length > 1);
  const duplicatePaths = new Set(duplicates.flatMap((group) => group.slice(1)));
  const records = all.filter((record) => !duplicatePaths.has(record.relativePath)).map((record, index) => ({ ...record, order: index }));
  if (records.some((record) => !record.day && !record.section)) throw new Error(`No se pudo asignar fecha o seccion a un archivo de ${config.slug}.`);
  return { sourceRoot, all, records, duplicates, sourceBytes };
}

function r2Config() {
  const accountId = required("R2_ACCOUNT_ID"); const bucket = required("R2_BUCKET_NAME"); const endpoint = required("R2_ENDPOINT").replace(/\/+$/, ""); const publicBaseUrl = required("NEXT_PUBLIC_MEDIA_BASE_URL").replace(/\/+$/, "");
  const endpointUrl = new URL(endpoint); const publicUrl = new URL(publicBaseUrl);
  if (endpointUrl.protocol !== "https:" || endpointUrl.pathname !== "/" || endpointUrl.host !== accountId + ".r2.cloudflarestorage.com") throw new Error("R2_ENDPOINT no coincide con el Account ID.");
  if (publicUrl.protocol !== "https:" || publicUrl.pathname !== "/" || publicUrl.host === endpointUrl.host) throw new Error("NEXT_PUBLIC_MEDIA_BASE_URL no es publica.");
  return { bucket, publicBaseUrl, client: new S3Client({ region: "auto", endpoint, forcePathStyle: true, credentials: { accessKeyId: required("R2_ACCESS_KEY_ID"), secretAccessKey: required("R2_SECRET_ACCESS_KEY") } }) };
}
function key(slug: string, mediaId: string, role: "full" | "thumbnail" | "video" | "poster") { const folder = role === "full" ? "images/full" : role === "thumbnail" ? "images/thumbs" : role === "video" ? "videos" : "posters"; return `trips/${slug}/${folder}/${mediaId}.${role === "video" ? "mp4" : "webp"}`; }
async function head(client: S3Client, bucket: string, objectKey: string) { try { return await client.send(new HeadObjectCommand({ Bucket: bucket, Key: objectKey })); } catch (error) { const candidate = error as { name?: string; $metadata?: { httpStatusCode?: number } }; if (candidate.name === "NotFound" || candidate.name === "NoSuchKey" || candidate.$metadata?.httpStatusCode === 404) return undefined; throw error; } }
async function put(config: ReturnType<typeof r2Config>, object: PreparedObject) { const remote = await head(config.client, config.bucket, object.key); if (remote?.Metadata?.sha256?.toLowerCase() === object.sha256) return "skipped" as const; if (remote) throw new Error("Conflicto de hash remoto en " + object.key + "."); await config.client.send(new PutObjectCommand({ Bucket: config.bucket, Key: object.key, Body: object.body, ContentLength: object.body.length, ContentType: object.contentType, CacheControl: cacheControl, Metadata: { sha256: object.sha256, source: "travel-magnets-city" } })); return "uploaded" as const; }
function run(command: string, args: string[]) { return new Promise<void>((resolve, reject) => { const child = spawn(command, args, { windowsHide: true }); let stderr = ""; child.stderr.on("data", (chunk) => { stderr += String(chunk); }); child.on("error", reject); child.on("close", (code) => code === 0 ? resolve() : reject(new Error(path.basename(command) + " fallo: " + stderr.slice(-500)))); }); }
function ffmpegPath() { return process.env.FFMPEG_PATH?.trim() || path.join(process.env.USERPROFILE || os.homedir(), "Downloads", "ffmpeg-8.0.1-essentials_build", "ffmpeg-8.0.1-essentials_build", "bin", "ffmpeg.exe"); }
async function prepareImage(record: SourceRecord, config: TripConfig): Promise<Prepared> { await fs.mkdir(derivativeRoot, { recursive: true }); const base = path.join(derivativeRoot, `${config.slug}-${record.mediaId}`); const fullPath = base + "-full.webp"; const thumbnailPath = base + "-thumb.webp"; const input = sharp(record.absolutePath).rotate(); const metadata = await input.metadata(); let full: Buffer; let thumbnail: Buffer; try { full = await fs.readFile(fullPath); thumbnail = await fs.readFile(thumbnailPath); } catch { full = await input.clone().resize({ width: 2400, withoutEnlargement: true }).webp({ quality: 84 }).toBuffer(); thumbnail = await input.clone().resize({ width: 720, withoutEnlargement: true }).webp({ quality: 78 }).toBuffer(); await fs.writeFile(fullPath, full); await fs.writeFile(thumbnailPath, thumbnail); } const dimensions = await sharp(full).metadata(); return { objects: [{ key: key(config.slug, record.mediaId, "full"), body: full, contentType: "image/webp", sha256: sha256(full) }, { key: key(config.slug, record.mediaId, "thumbnail"), body: thumbnail, contentType: "image/webp", sha256: sha256(thumbnail) }], mediaType: "image", width: dimensions.width ?? metadata.width ?? 1, height: dimensions.height ?? metadata.height ?? 1 }; }
async function prepareVideo(record: SourceRecord, config: TripConfig): Promise<Prepared> { await fs.mkdir(derivativeRoot, { recursive: true }); const base = path.join(derivativeRoot, `${config.slug}-${record.mediaId}`); const mp4Path = base + ".mp4"; const posterPath = base + ".jpg"; try { await fs.access(mp4Path); } catch { await run(ffmpegPath(), ["-y", "-i", record.absolutePath, "-c:v", "libx264", "-preset", "medium", "-crf", "23", "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart", mp4Path]); } try { await fs.access(posterPath); } catch { await run(ffmpegPath(), ["-y", "-ss", "1", "-i", record.absolutePath, "-frames:v", "1", "-q:v", "3", posterPath]); } const video = await fs.readFile(mp4Path); const poster = await sharp(posterPath).rotate().webp({ quality: 84 }).toBuffer(); const dimensions = await sharp(poster).metadata(); return { objects: [{ key: key(config.slug, record.mediaId, "video"), body: video, contentType: "video/mp4", sha256: sha256(video) }, { key: key(config.slug, record.mediaId, "poster"), body: poster, contentType: "image/webp", sha256: sha256(poster) }], mediaType: "video", width: dimensions.width ?? 1280, height: dimensions.height ?? 720 }; }
function altFor(record: SourceRecord) { return `Fotografia de ${record.place?.name ?? record.section?.title ?? "la ruta"}`; }
async function upsert(client: ReturnType<typeof createSupabaseAdminClient>, table: string, rows: Record<string, unknown>[], onConflict = "id") { for (let index = 0; index < rows.length; index += 100) { const result = await client.from(table).upsert(rows.slice(index, index + 100), { onConflict }); if (result.error) throw new Error(`${table}: ${result.error.message}`); } }
function mediaRow(config: TripConfig, record: SourceRecord, prepared: Prepared) { return { id: record.mediaId, trip_id: stableUuid(`trip:${config.slug}`), storage_key: key(config.slug, record.mediaId, prepared.mediaType === "video" ? "video" : "full"), thumbnail_key: prepared.mediaType === "image" ? key(config.slug, record.mediaId, "thumbnail") : null, poster_key: prepared.mediaType === "video" ? key(config.slug, record.mediaId, "poster") : null, media_type: prepared.mediaType, width: prepared.width, height: prepared.height, aspect_ratio: prepared.width / prepared.height, orientation: prepared.width === prepared.height ? "square" : prepared.width > prepared.height ? "landscape" : "portrait", alt: altFor(record), focus: { x: 50, y: 50 }, capture_date: record.date, capture_time: null, review_status: "selected", exclusion_reason: null, source_path_hash: record.sourcePathHash, metadata: { local_id: record.relativePath, original_file_name: record.originalFileName, source_folder: record.sourceFolder, source_path_hash: record.sourcePathHash, ...(record.date ? { day_key: record.date } : {}), city: record.place?.city ?? "", phase: record.day?.phase ?? "General", display_order: record.order, fit: "contain", admin_description: record.section ? record.section.description : `Importado desde ${config.title}.` } }; }
async function writeDatabase(config: TripConfig, records: SourceRecord[], preparedById: Map<string, Prepared>) { const client = createSupabaseAdminClient(); const tripId = stableUuid(`trip:${config.slug}`); const existing = await client.from("trips").select("id,status").eq("slug", config.slug).maybeSingle(); if (existing.error) throw new Error(existing.error.message); if (existing.data && !["draft", "published"].includes(String(existing.data.status))) throw new Error(`El viaje ${config.slug} no esta disponible para una importacion idempotente.`);
  await upsert(client, "trips", [{ id: tripId, slug: config.slug, title: config.title, start_date: config.startDate, end_date: config.endDate, summary: config.intro, status: existing.data?.status ?? "draft", hero_mode: "collage", theme: { country: config.country, dates: `${config.startDate} - ${config.endDate}`, intro: config.intro, route: config.route, closing: { title: "Fin del recorrido", body: `El album de ${config.title} termina aqui.` } } }]);
  const dayRows = config.days.map((day) => ({ id: stableUuid(`day:${config.slug}:${day.date}`), trip_id: tripId, day_number: day.number, date: day.date, title: day.title, location: day.location, phase: day.phase, summary: day.summary, display_order: day.number }));
  const placeDates = new Map<string, string>(); for (const record of records) if (record.place && record.day && !placeDates.has(record.place.key)) placeDates.set(record.place.key, record.day.date);
  const placeRows = config.places.map((place, index) => ({ id: stableUuid(`place:${config.slug}:${place.key}`), trip_id: tripId, slug: place.key, name: place.name, alternate_name: null, city: place.city, zone: place.zone, visit_date: placeDates.get(place.key) ?? null, summary: `Registro de ${place.name} en el recorrido de ${config.title}.`, description: `Lugar documentado en las fotografias del viaje ${config.title}.`, wikipedia_url: place.wikipediaUrl, category: place.category, latitude: place.latitude ?? null, longitude: place.longitude ?? null, display_order: index }));
  await upsert(client, "trip_days", dayRows); await upsert(client, "places", placeRows);
  const dayByDate = new Map(dayRows.map((row) => [String(row.date), row])); const placeByKey = new Map(placeRows.map((row, index) => [config.places[index].key, row]));
  const dayPlaceRows = config.places.flatMap((place) => { const dbPlace = placeByKey.get(place.key); const date = placeDates.get(place.key); const day = date ? dayByDate.get(date) : undefined; return dbPlace && day ? [{ trip_day_id: day.id, place_id: dbPlace.id, display_order: placeRows.indexOf(dbPlace) }] : []; });
  for (const day of dayRows) { const remove = await client.from("trip_day_places").delete().eq("trip_day_id", day.id); if (remove.error) throw new Error(remove.error.message); }
  if (dayPlaceRows.length) await upsert(client, "trip_day_places", dayPlaceRows, "trip_day_id,place_id");
  const mediaRows = records.map((record) => mediaRow(config, record, preparedById.get(record.mediaId)!)); await upsert(client, "media", mediaRows);
  const removeAssignments = await client.from("media_assignments").delete().eq("trip_id", tripId); if (removeAssignments.error) throw new Error(removeAssignments.error.message);
  const assignments: Record<string, unknown>[] = []; const firstByPlace = new Set<string>(); const firstByDay = new Set<string>(); const mosaicCountByDay = new Map<string, number>();
  for (const record of records) { const prepared = preparedById.get(record.mediaId)!; if (record.day) { const dayId = dayByDate.get(record.day.date)!.id; assignments.push({ trip_id: tripId, media_id: record.mediaId, trip_day_id: dayId, role: "day_gallery", display_order: record.order }); if (record.kind === "video") assignments.push({ trip_id: tripId, media_id: record.mediaId, trip_day_id: dayId, role: "day_video", display_order: record.order }); if (record.kind === "image" && !firstByDay.has(record.day.date)) { firstByDay.add(record.day.date); assignments.push({ trip_id: tripId, media_id: record.mediaId, trip_day_id: dayId, role: "day_hero", display_order: 0 }); } const mosaicCount = mosaicCountByDay.get(record.day.date) ?? 0; if (record.kind === "image" && mosaicCount < 3) { mosaicCountByDay.set(record.day.date, mosaicCount + 1); assignments.push({ trip_id: tripId, media_id: record.mediaId, trip_day_id: dayId, role: "day_mosaic", display_order: mosaicCount }); } } if (record.place) { const place = placeByKey.get(record.place.key); if (place) { assignments.push({ trip_id: tripId, media_id: record.mediaId, place_id: place.id, role: "place", display_order: record.order }); if (!firstByPlace.has(record.place.key) && prepared.mediaType === "image") { firstByPlace.add(record.place.key); assignments.push({ trip_id: tripId, media_id: record.mediaId, place_id: place.id, role: "place_cover", display_order: 0 }); } } } }
  const lastImage = [...records].reverse().find((record) => record.kind === "image"); if (lastImage) assignments.push({ trip_id: tripId, media_id: lastImage.mediaId, role: "closing", display_order: 0 }); if (assignments.length) await upsert(client, "media_assignments", assignments, "id");
  const sectionRows = config.sections.map((section, index) => ({ id: stableUuid(`section:${config.slug}:${section.key}`), trip_id: tripId, title: section.title, description: section.description, display_order: index, is_gallery: true, initially_closed: true })); await upsert(client, "trip_sections", sectionRows); const sectionIds = sectionRows.map((row) => row.id); for (const sectionId of sectionIds) { const remove = await client.from("trip_section_media").delete().eq("section_id", sectionId); if (remove.error) throw new Error(remove.error.message); } const sectionMediaRows = records.filter((record) => record.section).map((record) => ({ section_id: stableUuid(`section:${config.slug}:${record.section!.key}`), media_id: record.mediaId, display_order: record.order })); if (sectionMediaRows.length) await upsert(client, "trip_section_media", sectionMediaRows, "section_id,media_id");
  const imageIds = records.filter((record) => record.kind === "image").map((record) => record.mediaId); const videoId = records.find((record) => record.kind === "video")?.mediaId; const coverSets = [{ name: "a", layout: "collage", ids: imageIds.slice(0, 3) }, { name: "b", layout: "collage", ids: imageIds.slice(3, 6) }, { name: "c", layout: "collage", ids: imageIds.slice(6, 10) }, { name: "d", layout: videoId ? "video" : "collage", ids: videoId ? [videoId, ...imageIds.slice(10, 12)] : imageIds.slice(10, 13) }]; await upsert(client, "hero_sets", coverSets.map((set, index) => ({ id: stableUuid(`hero:${config.slug}:${set.name}`), trip_id: tripId, name: set.name, layout: set.layout, display_order: index, is_active: index === 0 }))); for (const set of coverSets) { const heroId = stableUuid(`hero:${config.slug}:${set.name}`); const remove = await client.from("hero_set_media").delete().eq("hero_set_id", heroId); if (remove.error) throw new Error(remove.error.message); if (set.ids.length) await upsert(client, "hero_set_media", set.ids.map((mediaId, slot) => ({ hero_set_id: heroId, media_id: mediaId, slot, display_order: slot, focus: { x: 50, y: 50 } })), "hero_set_id,media_id"); } const publish = await client.from("trips").update({ status: "published" }).eq("id", tripId); if (publish.error) throw new Error(publish.error.message); }

async function prepareAll(config: TripConfig, records: SourceRecord[], r2: ReturnType<typeof r2Config>, upload: boolean) { const preparedById = new Map<string, Prepared>(); const counts = { images: 0, videos: 0, objects: 0, uploaded: 0, skipped: 0, bytes: 0 }; for (const record of records) { const prepared = record.kind === "video" ? await prepareVideo(record, config) : await prepareImage(record, config); preparedById.set(record.mediaId, prepared); if (record.kind === "video") counts.videos += 1; else counts.images += 1; for (const object of prepared.objects) { counts.objects += 1; counts.bytes += object.body.length; if (upload) { const state = await put(r2, object); counts[state] += 1; } } } return { preparedById, counts }; }
async function publicCheck(config: TripConfig, records: SourceRecord[], r2: ReturnType<typeof r2Config>) { let missing = 0; let rangeErrors = 0; const urls = new Set<string>(); for (const record of records) { const roles: Array<"full" | "thumbnail" | "video" | "poster"> = record.kind === "video" ? ["video", "poster"] : ["full", "thumbnail"]; for (const role of roles) { const url = `${r2.publicBaseUrl}/${key(config.slug, record.mediaId, role)}`; urls.add(url); const response = await fetch(url, { method: "GET" }); if (!response.ok) missing += 1; await response.arrayBuffer(); if (role === "video") { const range = await fetch(url, { headers: { Range: "bytes=0-15" } }); if (range.status !== 206) rangeErrors += 1; await range.arrayBuffer(); } } } return { objects: urls.size, missing, rangeErrors }; }
async function verifyTrip(config: TripConfig, r2: ReturnType<typeof r2Config>) { const client = createSupabaseAdminClient(); const trip = await client.from("trips").select("id,status").eq("slug", config.slug).maybeSingle(); if (trip.error) throw new Error(trip.error.message); if (!trip.data) throw new Error(`No existe ${config.slug}.`); const media = await client.from("media").select("id,storage_key,thumbnail_key,poster_key,media_type").eq("trip_id", trip.data.id); if (media.error) throw new Error(media.error.message); let missing = 0; let rangeErrors = 0; for (const row of media.data ?? []) { const keys = row.media_type === "video" ? [row.storage_key, row.poster_key] : [row.storage_key, row.thumbnail_key]; for (const objectKey of keys.filter(Boolean) as string[]) { const remote = await head(r2.client, r2.bucket, objectKey); if (!remote) missing += 1; if (row.media_type === "video" && objectKey === row.storage_key) { const range = await fetch(`${r2.publicBaseUrl}/${objectKey}`, { headers: { Range: "bytes=0-15" } }); if (range.status !== 206) rangeErrors += 1; await range.arrayBuffer(); } } } console.log(`${config.slug}: status=${trip.data.status}; medios=${media.data?.length ?? 0}; objetos_faltantes=${missing}; range_errors=${rangeErrors}`); if (missing || rangeErrors) throw new Error(`Verificacion R2 fallida para ${config.slug}.`); }
function report(config: TripConfig, scanResult: Awaited<ReturnType<typeof scan>>, counts: { images: number; videos: number; objects: number; uploaded: number; skipped: number; bytes: number }) { const reportPath = path.join(projectRoot, "docs", `${config.slug}-import-report.md`); const duplicateLines = scanResult.duplicates.length ? scanResult.duplicates.map((group) => `- ${group.join(", ")}`).join("\n") : "- Ninguno"; const sectionLines = config.sections.length ? config.sections.map((section) => `- ${section.title}: ${scanResult.records.filter((record) => record.section?.key === section.key).length} medios; cerrada inicialmente.`).join("\n") : "- Ninguna"; const content = `# Informe de importacion: ${config.title}\n\n- Origen: Downloads/${config.folder} (ruta local no publicada)\n- Fechas detectadas: ${config.startDate} a ${config.endDate}\n- Viaje: ${config.title} (${config.slug})\n- Fuente de verdad: Supabase; medios publicos: Cloudflare R2.\n\n## Estructura\n\n${scanResult.all.map((record) => `- ${record.sourceFolder}`).filter((value, index, values) => values.indexOf(value) === index).join("\n")}\n\n## Jornadas\n\n${config.days.map((day) => `- Dia ${day.number}: ${day.date} - ${day.title}`).join("\n")}\n\n## Secciones sin fecha\n\n${sectionLines}\n\n## Lugares\n\n${config.places.map((place) => `- ${place.name}${place.wikipediaUrl ? ` - ${place.wikipediaUrl}` : ""}`).join("\n")}\n\n## Medios\n\n- Archivos fuente: ${scanResult.all.length}\n- Importados tras duplicados exactos: ${scanResult.records.length}\n- Imagenes: ${counts.images}\n- Videos: ${counts.videos}\n- Objetos previstos: ${counts.objects}\n- Bytes derivados previstos: ${counts.bytes}\n- Duplicados exactos omitidos: ${scanResult.duplicates.reduce((total, group) => total + group.length - 1, 0)}\n\n## R2 y Supabase\n\n- Objetos subidos: ${counts.uploaded}\n- Objetos reutilizados por hash: ${counts.skipped}\n- Claves estables bajo trips/${config.slug}/.\n- Registros y asignaciones idempotentes por UUID estable.\n- Galerias cerradas inicialmente.\n\n## Incertidumbres\n\n- Las carpetas sin fecha se mantienen como secciones generales; no se inventan jornadas.\n- Los enlaces de Wikipedia se incluyen solo cuando hay articulo verificado en espanol.\n- Los originales permanecen en Downloads y no forman parte del repositorio.\n\n## Duplicados exactos\n\n${duplicateLines}\n`; return fs.writeFile(reportPath, content, "utf8"); }

async function main() { const r2 = r2Config(); for (const config of configs) { const result = await scan(config); if (mode === "dry-run") { const prepared = await prepareAll(config, result.records, r2, false); await report(config, result, prepared.counts); console.log(`${config.slug}: source=${result.all.length}; imported=${result.records.length}; images=${prepared.counts.images}; videos=${prepared.counts.videos}; objects=${prepared.counts.objects}; bytes=${prepared.counts.bytes}; duplicates=${result.all.length - result.records.length}`); continue; } if (mode === "import") { const prepared = await prepareAll(config, result.records, r2, true); await writeDatabase(config, result.records, prepared.preparedById); await verifyTrip(config, r2); const publicResult = await publicCheck(config, result.records, r2); if (publicResult.missing || publicResult.rangeErrors) throw new Error(`Verificacion publica fallida para ${config.slug}.`); await report(config, result, prepared.counts); console.log(`${config.slug}: importado y publicado; subidos=${prepared.counts.uploaded}; omitidos=${prepared.counts.skipped}; objetos=${prepared.counts.objects}; publicos_200=${publicResult.objects}`); continue; } await verifyTrip(config, r2); const publicResult = await publicCheck(config, result.records, r2); if (publicResult.missing || publicResult.rangeErrors) throw new Error(`Verificacion publica fallida para ${config.slug}.`); console.log(`${config.slug}: publicos_200=${publicResult.objects}; range_errors=${publicResult.rangeErrors}`); } }
main().catch((error) => { console.error(error instanceof Error ? error.message : "Error de importacion"); process.exitCode = 1; });
