import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { getAdminTrip } from "@/lib/admin/data";
import { publishTrip, saveTrip, unpublishTrip } from "@/lib/admin/actions";
import { ConfirmSubmit } from "@/components/admin/ConfirmSubmit";

export default async function AdminTripPage({ params, searchParams }: { params: Promise<{ tripId: string }>; searchParams: Promise<{ error?: string }> }) {
  const { client } = await requireAdmin();
  const { tripId } = await params;
  const query = await searchParams;
  const trip = await getAdminTrip(client, tripId);
  if (!trip) return null;
  const active = trip.media.filter((item) => item.reviewStatus === "selected").length;
  const pending = trip.media.filter((item) => item.reviewStatus === "pending").length;
  const theme = trip.theme;
  return <section className="admin-section"><div className="admin-page-heading"><div><span className="section-label">Viaje</span><h1>{trip.title}</h1><p>{trip.startDate} - {trip.endDate}</p></div><div className="admin-card-actions"><Link className="admin-primary-link" href={`/admin/viajes/${trip.slug}/preview`} target="_blank">Vista previa</Link>{trip.status === "published" ? <Link href={`/viajes/${trip.slug}`} target="_blank">Web publica</Link> : <span className="admin-status admin-status--draft">Solo borrador</span>}</div></div>
    {query.error && <p className="admin-message admin-message--error">{query.error}</p>}
    <div className="admin-stats"><div><strong>{trip.status === "published" ? "Publicado" : trip.status}</strong><span>Estado</span></div><div><strong>{trip.days.length}</strong><span>Jornadas</span></div><div><strong>{trip.places.length}</strong><span>Lugares</span></div><div><strong>{active}</strong><span>Medios activos</span></div><div><strong>{pending}</strong><span>Pendientes</span></div><div><strong>{trip.heroSets.length}</strong><span>Portadas</span></div></div>
    <form action={saveTrip} className="admin-editor-card"><input type="hidden" name="tripId" value={trip.id} /><input type="hidden" name="currentSlug" value={trip.slug} /><div className="editor-card-heading"><strong>Informacion general</strong><span>Los cambios se guardan en Supabase al enviarlos.</span></div><div className="admin-form-grid"><label>Titulo<input name="title" defaultValue={trip.title} required /></label><label>Slug<input name="slug" defaultValue={trip.slug} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><label>Fecha inicial<input type="date" name="startDate" defaultValue={trip.startDate} required /></label><label>Fecha final<input type="date" name="endDate" defaultValue={trip.endDate} required /></label><label>Modo de portada<select name="heroMode" defaultValue={trip.heroMode}><option value="collage">Collage</option><option value="slideshow">Slideshow</option><option value="video">Video</option></select></label><label>Tema visual<input name="visualTheme" defaultValue={typeof theme.visualTheme === "string" ? theme.visualTheme : ""} /></label><label className="field-wide">Resumen<input name="summary" defaultValue={trip.summary} required /></label><label className="field-wide">Introduccion<textarea name="intro" defaultValue={trip.intro} rows={4} /></label><label className="field-wide">Ruta visible<textarea name="route" defaultValue={trip.route.map((point) => `${point.name} | ${point.region}`).join("\n")} rows={5} placeholder="Ciudad | contexto" /></label><label>Cierre titulo<input name="closingTitle" defaultValue={trip.closingTitle} /></label><label className="field-wide">Cierre texto<textarea name="closingBody" defaultValue={trip.closingBody} rows={3} /></label></div><button className="admin-primary-link" type="submit">Guardar viaje</button></form>
    <div className="admin-link-grid"><Link href={`/admin/viajes/${trip.slug}/medios`}><strong>Gestionar medios</strong><span>Subir, revisar, filtrar y asignar.</span></Link><Link href={`/admin/viajes/${trip.slug}/dias`}><strong>Editar jornadas</strong><span>Crear, ordenar y conectar lugares.</span></Link><Link href={`/admin/viajes/${trip.slug}/secciones`}><strong>Secciones sin fecha</strong><span>Galerias generales y recuerdos ordenados.</span></Link><Link href={`/admin/viajes/${trip.slug}/lugares`}><strong>Editar lugares</strong><span>Fichas, coordenadas y relaciones.</span></Link><Link href={`/admin/viajes/${trip.slug}/portadas`}><strong>Gestionar portadas</strong><span>Slots, foco y variante activa.</span></Link><Link href={`/admin/viajes/${trip.slug}/nfc`}><strong>NFC y QR</strong><span>Codigo estable y estado de resolucion.</span></Link></div>
    <div className="admin-publish-box"><div><strong>Publicacion</strong><p>Valida jornadas, portadas y medios antes de mostrar este viaje.</p></div>{trip.status === "published" ? <form action={unpublishTrip}><input type="hidden" name="tripSlug" value={trip.slug} /><ConfirmSubmit className="admin-secondary-link" message="Despublicar este viaje? Dejara de estar disponible para visitantes.">Despublicar</ConfirmSubmit></form> : <form action={publishTrip}><input type="hidden" name="tripSlug" value={trip.slug} /><ConfirmSubmit className="admin-primary-link" message="Publicar este viaje?">Publicar viaje</ConfirmSubmit></form>}</div>
  </section>;
}
